# Custom

condense_wildcard_suffixes = true
edition = "2021"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_layout = "Vertical"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
unstable_features = true
use_try_shorthand = true
wrap_comments = true


# Defaults

# array_width = 60
# attr_fn_like_width = 70
# binop_separator = "Front"
# blank_lines_lower_bound = 0
# blank_lines_upper_bound = 1
# brace_style = "SameLineWhere"
# chain_width = 60
# color = "Auto"
# combine_control_expr = true
# comment_width = 80
# control_brace_style = "AlwaysSameLine"
# disable_all_formatting = false
# doc_comment_code_block_width = 100
# empty_item_single_line = true
# enum_discrim_align_threshold = 0
# error_on_line_overflow = false
# error_on_unformatted = false
# fn_call_width = 60
# fn_params_layout = "Tall"
# fn_single_line = false
# force_explicit_abi = true
# force_multiline_blocks = false
# format_generated_files = true
# format_macro_bodies = true
# hard_tabs = false
# hide_parse_errors = false
# ignore = []
# imports_indent = "Block"
# indent_style = "Block"
# inline_attribute_width = 0
# match_arm_blocks = true
# match_arm_leading_pipes = "Never"
# match_block_trailing_comma = false
# max_width = 100
# merge_derives = true
# newline_style = "Auto"
# remove_nested_parens = true
# reorder_imports = true
# reorder_modules = true
# short_array_element_width_threshold = 10
# skip_children = false
# skip_macro_invocations = []
# single_line_if_else_max_width = 50
# space_after_colon = true
# space_before_colon = false
# spaces_around_ranges = false
# struct_field_align_threshold = 0
# struct_lit_single_line = true
# struct_lit_width = 18
# struct_variant_width = 35
# tab_spaces = 4
# trailing_comma = "Vertical"
# trailing_semicolon = true
# type_punctuation_density = "Wide"
# use_small_heuristics = "Default"
# version = "One"
# where_single_line = false