[package]
name = "uri-template-system-core"
authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true

[dependencies]
anyhow = "1"
fnv = "1"
paste = "1"

[dev-dependencies]
criterion = "0.5"
iri-string = "0.7"
uri-template-system-fixtures = { path = "../fixtures" }
uritemplate-next = "0.2"

[[bench]]
name = "comparison"
harness = false

[[bench]]
name = "optimisation"
harness = false
