name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: swatinem/rust-cache@v2
      with:
        shared-key: "ci"
    - name: Lint
      run: cargo clippy
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
